# Generated by Django 3.0.6 on 2020-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
