# Generated by Django 3.0.6 on 2020-07-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_auto_20200706_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
